# Copyright (C) 2013-2017 Instapio Inc - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# http://instap.io info@instapio.com @instapio
FROM mhart/alpine-node:base-6
ADD  . .
EXPOSE 8080
CMD ["node", "index.js"]